import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View } from 'react-native';
import Main from './Main'
import { NativeRouter, Routes, Route, Link } from 'react-router-native';

// import Amplify from 'aws-amplify';
// import config from '.src/aws-exports'; // the configuration file generated by Amplify CLI

// Amplify.configure(config);

export default function App() {
  return (
    <NativeRouter>
      <Routes>
        <Route exact path = "/" element={<Main />} />
      </Routes>
    </NativeRouter>
    
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
